### ISSUE TITLE
EC2 HTTPS & Load Balancers

### ISSUE THREAD

**Issue by cutegyuseok** [Final-Project-Team6/BE_Project#11]
## Title
HTTPS 적용

## Description
![image](https://github.com/Final-Project-Team6/BE_Project/assets/103543611/705f83eb-54de-48d3-96dd-87e5ea7ba210)

## Tasks
- [x] 도메인 생성
- [x] security 정책 설정
- [x] SSL 인증서 발급 & 호스팅 적용
- [x] route53 도메인 연결
- [x] Target 그룹 지정
- [x] Load Balancer 생성 및 적용

**Comment by cutegyuseok** [comment]
SSL 인증서 발급 후 모두 적용했지만 인증서가 적용되지 않아 다시 처음부터 하는중입니다 ㅠㅠ

**Comment by cutegyuseok** [comment]
![image](https://github.com/Final-Project-Team6/BE_Project/assets/103543611/51074511-95b9-4f5c-bfc6-f95ef6882e31)
![image](https://github.com/Final-Project-Team6/BE_Project/assets/103543611/31349f66-2007-4c4a-b8b4-41097ffe505c)
해결했습니다~
